name: Build

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Check for image changes
        id: containerfiles
        uses: tj-actions/changed-files@47
        with:
          dir_names: "true"
          files: |
            Containerfile

      - name: Login to GHCR
        if: steps.containerfiles.outputs.any_changed == "true"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push container images
        if: steps.containerfiles.outputs.any_changed == "true"
        env:
          CHANGED_FILES: ${{ steps.containerfiles.outputs.all_changed_files }}
        run: |
          for file in ${CHANGED_FILES}; do
            docker build -f $file/Containerfile -t ghcr.io/${{ github.repository }}:${GITHUB_RUN_NUMBER} ./$file
            docker build -f $file/Containerfile -t ghcr.io/${{ github.repository }}:latest ./$file
            docker push ghcr.io/${{ github.repository }}:${GITHUB_RUN_NUMBER}
            docker push ghcr.io/${{ github.repository }}:latest
          done
