name: Manual build
# This is a completely manual action to be run if the automated one stops working or skips something.
# Edit to build what is needed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: Ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build
        run:
          docker build -f neovim/Containerfile -t ghcr.io/hardomx/nvim-containers-neovim:${GITHUB_RUN_NUMBER} -t ghcr.io/hardomx/nvim-containers-neovim:latest ./neovim
          docker push ghcr.io/hardomx/nvim-containers-neovim:${GITHUB_RUN_NUMBER}
          docker push ghcr.io/hardomx/nvim-containers-neovim:latest

          docker build -f python/Containerfile -t ghcr.io/hardomx/nvim-containers-python:${GITHUB_RUN_NUMBER} -t ghcr.io/hardomx/nvim-containers-python:latest ./python
          docker push ghcr.io/hardomx/nvim-containers-python:${GITHUB_RUN_NUMBER}
          docker push ghcr.io/hardomx/nvim-containers-python:latest

          docker build -f go/Containerfile -t ghcr.io/hardomx/nvim-containers-go:${GITHUB_RUN_NUMBER} -t ghcr.io/hardomx/nvim-containers-go:latest ./go
          docker push ghcr.io/hardomx/nvim-containers-go:${GITHUB_RUN_NUMBER}
          docker push ghcr.io/hardomx/nvim-containers-go:latest
